### ISSUE TITLE
Swapping object from 1 list to another

### ISSUE THREAD

**Issue by MohawkMan** [AutoMapper/AutoMapper.Collection#84] opened 2018-05-11 00:57 UTC
I am not sure if this is an issue or not. 
I have an object<foo> that has list1 = List<bar> and list2 = list<bar>. 

When I move a bar from 1 list to another, the mapping part works fine but when I try to save the changes (using EF) it throws and error ... "cannot be tracked because another instance with the same key value for {'Id'} is already being tracked"

I assume Collection is treating each list independently so it is trying to delete bar to remove it from list1 and then it creates a new bar to add it to list2, which is causing a same key error. Is that assumption correct and is there any way around it?

**Comment by TylerCarlson1** [comment] 2018-05-11 14:05
if one of the collections is not EF objects, then there's no way to track that back to EF as a delete.
And if it is it might be trying to orphan that entry instead of deleting it based on the relationship between the two. See #4 

For things like this you have to use an after map to transfer items around usually.  It creates a duplicate of the class and moving the original class around between the two lists is much easier IMO.

**Closed** 2022-10-18 05:56 UTC
